
import { PlanPhase } from '../types';

export const phase1: PlanPhase = { 
  id: 1, 
  title: "FEAT: 4-TAB AUDIT SUITE (THE BIBLE)", 
  desc: "Design System, A11y, UX, Prototype.",
  tools: ["Kimi K2.5", "Algorithmic Checks"],
  cost: "DEV: €0.01 | USER: 2 Credits/Fix (~€0.50)",
  details: "Implementazione tecnica dell'Audit Engine. Include la 'Antigravity Bible' con 20 regole fondamentali e protocolli anti-Beacon.",
  prompts: [
    "SYSTEM ROLE: Senior Design Auditor & Engineering Lead.",
    "*** THE ANTIGRAVITY BIBLE (STRICT AUDIT RULES) ***\n\n0. COMPONENT CONTRACT VALIDATOR (KILLER FEATURE)\nOgni componente deve avere: Variants (Default, Hover, Focus, Disabled), Token-Only Styling (No Hex), Responsive Rules, Code Mapping, A11y Metadata.\n\n1. HEURISTIC AUDIT\n- Visibility: Loader/Feedback sempre presenti.\n- Match real world: Naming coerente.\n- Control: Undo/Back sempre presenti.\n- Error Prevention: Conferme distruttive.\n- Recognition: No memory load.\n- Flexibility: Shortcut/Bulk actions.\n- Aesthetic: No ridondanze.\n- Recovery: Error copy azionabile.\n- Help: Tooltips.\n\n2. CONTENT & TONE\n- Active Verbs (Salva vs Ok).\n- Consistency formale.\n- Error struct: What+Why+Fix.\n- No dark patterns.\n- Localized formats (Date/Currency).\n- Truncation handling.\n\n3. I18N & LOCALIZATION\n- Plural rules (0,1,many).\n- No string concatenation.\n- RTL readiness.\n- Text expansion (+30% buffer).\n- No hardcoded breaks.\n\n4. INTERACTION STATES\n- Must have: Default, Hover, Pressed, Focus, Disabled, Loading, Error, Success, Read-only.\n\n5. FORM UX\n- Visible Labels.\n- Helper/Error text layout stability.\n- Required indicators.\n- Inline validation.\n- Password show/hide.\n- Input types (email, tel).\n\n6. DATA TABLES\n- Alignment (Numbers right).\n- Sticky headers.\n- Sort/Filter.\n- Empty/Loading states.\n- Pagination vs Infinite.\n- Bulk actions.\n\n7. TOKEN GOVERNANCE\n- No Raw Hex.\n- Semantic Priority (usage over primitive).\n- Naming conventions.\n- Deprecation checks.\n\n8. MOTION\n- Standard durations (150-300ms).\n- Reduced motion support.\n- Skeleton > Spinner.\n\n9. RESPONSIVE\n- Breakpoints map.\n- Reflow logic.\n- Max-width containers.\n- Safe Areas (notch).\n\n10. IA & NAVIGATION\n- Breadcrumbs.\n- Active state indicators.\n- Back navigation logic.\n\n11. ERROR HANDLING\n- Edge cases (Long names, Huge numbers).\n- Empty/Partial data.\n- Network errors (404/500).\n\n12. SECURITY UI\n- Data masking (PII).\n- Destructive confirmations.\n- Danger zones.\n- Consent patterns.\n\n13. API DESIGN\n- Props standard.\n- Boolean naming.\n- Slot composition.\n- A11y props required.\n\n14. SEMANTICS\n- HTML5 structure (<nav>, <main>).\n- Headings hierarchy.\n- Button vs Link.\n\n15. PERFORMANCE\n- Limit nesting depth.\n- Optimize assets (SVG, IMG).\n\n16. VISUAL QA\n- Snapshot baseline.\n- Typography drift.\n\n17. GOVERNANCE\n- Component creation rules.\n- Versioning.\n\n18. ETHICS\n- Inclusive language.\n- Color blindness checks.\n\n19. SAFETY (ANTI-HALLUCINATION)\n- Reuse existing components.\n- No token guessing.\n\n20. OUTPUT STANDARD\n- JSON: { id, category, severity, nodeId, description, suggestedFix, autoFixAvailable }.",
    "*** BEACON PARITY & SUPERIORITY (COMPETITOR KILLER) ***\nPer superare Beacon, aggiungiamo regole di Audit avanzate che vanno oltre il semplice linting visivo:\n\n1. GHOST NODE DETECTION (Hygiene):\n- Rilevare Frame vuoti, Gruppi inutili o layer con opacità 0% che 'sporcano' il DOM e il codice.\n- Output: \"Clean up 12 ghost nodes\".\n\n2. COMPLEX CONTRAST ANALYSIS (Vision):\n- Non limitarsi a Testo su Sfondo Solido. Analizzare Testo su Immagine/Gradiente.\n- Se il contrasto è a rischio, suggerire: \"Add scrim/overlay\" o \"Text Shadow\".\n\n3. LOCALIZATION STRESS TEST (Layout):\n- Simulare espansione del testo in lingue verbose (Tedesco +30%, Finlandese).\n- Se il container ha width fissa e rompe il layout, segnalare: \"High Risk for Localization\".\n\n4. TOUCH TARGET HEATMAP (Mobile):\n- Non solo controllare la dimensione (44px), ma la vicinanza. Se due link sono troppo vicini (<8px), segnalare \"Fat Finger Risk\".\n\n5. CONSISTENCY ACROSS PAGES:\n- Beacon controlla la pagina corrente. Comtra deve controllare la coerenza tra pagine (es. Header diverso in Home vs Dettaglio).",
    "*** UX LEAD STRUCTURED REVIEW (Tab 3: UX Audit) ***\nEcco come ottenere una review strutturata, con metriche e insight decisamente più applicabili.\n\n\"Agisci come UX Lead per un SaaS B2B. Il prodotto che devi analizzare riguarda [mercato/business/obiettivi].\n\nAnalizza e restituisci:\n\n1) X problemi chiave secondo le euristiche Nielsen\n2) Evidenze testuali con esempi\n3) Impatto sul business basato su benchmark di mercato (1–5)\n4) Fix suggerito con motivazione\n\nOutput in tabella: problema | evidenza | impatto | fix\"\n\nIn sostanza: forzi ChatGPT (o altro LLM, come Claude) a lavorare per criteri \"scientifici\" e priorità concrete, evitando risposte discorsive e astratte.",
    "TASK: Analizza il JSON in input e applica rigorosamente queste regole. Genera un report JSON strutturato diviso per categorie.",
    "*** PROTOCOLLI DI ANALISI DESIGN SYSTEM (5. Gestione Design System) ***\n\n5.1 Token\n- Estratti automaticamente da Figma (JSON o raw CSS)\n- Tipologie supportate:\n  - Color tokens (palette principale, secondary, semantic)\n  - Typography (font-family, font-weight, font-size, line-height)\n  - Spacing (margins, paddings)\n  - Border radius / corner tokens\n  - Shadows, opacity, z-index\n  - Themes (Light / Dark)\n- Ogni token può avere note su accessibilità e responsive\n- Possibilità di esportare in JSON, SCSS o CSS custom properties\n\n5.2 Palette colori\n- Stories automatiche per ogni palette\n- Contrasto verificato (WCAG AA/AAA)\n- Possibilità di generare componenti con hover, focus e disabled states\n\n5.3 Tipografia\n- Scale tipografiche definite nel DS\n- Stories generate per H1-H6, paragraph, captions\n- Controllo responsive e line-height automatico\n\n5.4 Spacing & Border Radius\n- Token applicabili a componenti\n- Stories generate per padding/margin variations\n- Possibilità di switch per responsive scale\n\n5.5 Themes\n- Light & Dark mode\n- Sincronizzazione automatica tra i due\n- Possibilità di generare toggle components per la demo\n\n5.6 Grids & Layout\n- Stories con griglie predefinite\n- Componenti adattivi\n- Accessibilità garantita con focus & landmarks\n\n*** PROTOCOLLI ACCESSIBILITÀ (9. Accessibilità) ***\n- WCAG AA / AAA compliance\n- Contrasto automatico per colori\n- Focus states predefiniti e navigazione completa da tastiera\n- Supporto per screen reader\n- Alt text e descrizioni automatiche per immagini\n- ARIA roles solo se strettamente necessari\n- Generazione di note e suggerimenti pratici per developers"
  ],
  section: "CORE FEATURES & LOGIC"
};
