
import { PlanPhase } from '../types';

export const phase19: PlanPhase = {
  id: 19,
  title: "Growth: Gamification Engine",
  desc: "Levels, Badges & Certifications.",
  tools: ["React", "LinkedIn API"],
  cost: "DEV: €0 | USER: N/A",
  details: "Sistema di retention basato su XP e Medaglie. Integrazione 'Add to Profile' di LinkedIn per viralità professionale.",
  prompts: [
    "SYSTEM ROLE: Game Designer & Growth Hacker.",
    "*** GAMIFICATION RULES & SCORING ***",
    "1. XP CALCULATION:",
    "- Wireframe Generated: 10 XP",
    "- Audit Performed (A11y/UX/Proto): 5 XP",
    "- Sync Action (Storybook/Git): 20 XP (High value behavior)",
    "- Affiliate Invite: 50 XP (Viral growth)",
    "2. PROGRESSIVE LEVEL SYSTEM (DIFFICULTY CURVE):",
    "- L'accumulo di livelli deve diventare esponenzialmente più difficile per mantenere il valore dei rank alti.",
    "- Formula Soglia XP: `Threshold = 100 * (Level ^ 1.5)` (Approssimato).",
    "- Level 1 -> 2: Richiede 100 XP totali (Easy, ~10 azioni).",
    "- Level 2 -> 3: Richiede 300 XP totali (+200 XP).",
    "- Level 3 -> 4: Richiede 600 XP totali (+300 XP).",
    "- Level 4 -> 5 (Silver): Richiede 1000 XP totali (+400 XP).",
    "- Level 9 -> 10 (Legend): Richiede 3500 XP totali. Serve impegno costante.",
    "3. BADGES (UNLOCKABLES):",
    "- Leaf (Novice): Start.",
    "- Rock (Solid): 500 XP.",
    "- Iron (Engineer): > 10 Syncs.",
    "- Bronze (Auditor): > 50 Audits.",
    "- Diamond (Partner): > 5 Affiliates.",
    "4. LINKEDIN CERTIFICATION (ADD TO PROFILE):",
    "- Al posto di uno share generico, usa l'URL 'https://www.linkedin.com/profile/add'.",
    "- Compila automaticamente: Name='Level [X] Design Engineer', Organization='Comtra AI', IssueDate=Now, CertID='XP-[Total]'.",
    "- Questo crea una certificazione ufficiale sul profilo dell'utente, aumentando l'autorità del tool.",
    "- FUTURE TODO: È necessario diventare **LinkedIn Verified Partner** per bloccare i campi (titolo/organizzazione) e impedire che l'utente modifichi i dati della certificazione manualmente.",
    "5. DYNAMIC PRICING REWARDS (SUSTAINABLE):",
    "- Premia gli utenti attivi con sconti sul Piano Annuale (€250) per aumentare LTV e Cash Flow.",
    "- Formula: `Discount% = min(20, floor(Level / 5) * 5)`.",
    "- Level 1-4: 0%",
    "- Level 5 (Silver): 5% OFF (€237.50). *Trigger: Level Up Popup + Confetti*.",
    "- Level 10 (Legend): 10% OFF (€225.00).",
    "- Level 20 (God): 20% OFF (€200.00). Cap massimo per garantire margine.",
    "- Visualizzazione: Testo giallo sotto la barra XP: 'Current Reward: X% OFF Annual Plan'.",
    "TASK: Implementare la vista Analytics con il calcolo XP progressivo, le nuove icone badge e il widget 'Add to LinkedIn'."
  ],
  section: "MARKETING & LAUNCH"
};
