
import { PlanPhase } from '../types';

export const phase3: PlanPhase = { 
  id: 3, 
  title: "FEAT: CODE (Tokens, Target, Sync)", 
  desc: "Export 3-Mode: CSS, React, Drift.",
  tools: ["Kimi K2.5", "React Generator"],
  cost: "DEV: €0.02 | USER: 5 Credits (~€1.25)",
  details: "Implementazione della pipeline di esportazione codice e conversione token. Regole di sintassi definite nel Prompt.",
  prompts: [
    "SYSTEM ROLE: Senior React Engineer.",
    "*** CONTEXT & LOGIC RULES (DA IMPLEMENTARE) ***\nTAB 1: TOKENS & CSS (Global)\n- Logic: Gestione a Doppio Timestamp.\n- Stato 1 (Generazione): Quando l'utente clicca 'Generate CSS', salva `lastGeneratedCssDate`. Mostra il codice e il timestamp 'Last Updated'.\n- Stato 2 (Sync Storybook): Quando l'utente clicca 'Sync Storybook', salva `lastSyncedStorybookDate`. Mostra 'Synced: [Date]'.\n- Stato Bottone Sync: Se `lastSyncedStorybookDate >= lastGeneratedCssDate`, il bottone diventa DISABILITATO con testo 'Synced' (Niente da aggiornare). Se l'utente rigenera il CSS (nuovo timestamp > sync timestamp), il bottone torna ATTIVO con testo 'Update Storybook'.\n\nTAB 2: TARGET (Single Component)\n- Azione: Prende il layer selezionato.\n- AI Process: Converte in React/Vue/Liquid. IMPORTANTE: Sostituisce i valori HEX con le variabili CSS generate nel Tab 1.\n- SMART ROUTING: Verificare che due CTA identiche con destinazioni diverse generino rotte diverse nel codice (es. /login vs /signup basandosi sul transitionNodeID).\n\nTAB 3: SYNC (Drift Detection)\n- Azione: Confronta `FigmaNode.hash` con `StorybookComponent.args`.\n- Drift Logic: Se Figma ha una prop 'Size=XL' ma Storybook supporta solo 'SM/LG', segna come 'DRIFT'.",
    "*** SCENARI & ESEMPI REALI (CODE EXPORT) ***\nScenario A: Token Mapping (Fondamentale)\n- Input Figma: Rettangolo #FF0000, BorderRadius 8px.\n- Context: Tokens { \"sys.color.error\": \"#FF0000\", \"sys.radius.sm\": \"8px\" }.\n- Output React: <div className=\"bg-sys-error rounded-sm ...\"> (NON bg-[#FF0000]).\n\nScenario B: Drift Detection (Sync Tab)\n- Figma Component: Button { padding: 16px }.\n- Storybook Code: Button { padding: 12px }.\n- Output UI: Card rossa \"Drift Detected\". Messaggio: \"Padding inconsistency: Figma 16px vs Code 12px\". CTA: \"Update Figma\" o \"Push to Code\".\n\nScenario C: Componente Sconosciuto\n- Input: Frame disegnato a mano che sembra una Card.\n- Action AI: Riconosce il pattern. Genera codice React <Card> standard ma avvisa: \"Struttura non mappata a componente master\".",
    "TASK: Converti il JSON Figma in codice di produzione rispettando le regole sopra.",
    "*** REGOLE GENERAZIONE CODICE (8. Generazione codice) ***\n\n8.1 Linguaggi supportati\n- React + Tailwind (JSX/TSX)\n- Storybook (.stories.tsx)\n- Shopify (Liquid)\n- HTML + Clean CSS\n- Vue 3\n- Svelte\n- Angular (TS)\n\n8.2 Struttura cartelle (Esempio React)\n/src\n  /components\n    /Button\n      Button.tsx\n      Button.stories.tsx\n      Button.module.css\n    /Card\n      Card.tsx\n      Card.stories.tsx\n      Card.module.css\n\n8.3 Naming conventions\n- Componenti: PascalCase (Button, Card)\n- Files CSS: kebab-case (button.module.css)\n- Tokens: camelCase (primaryColor, spacingSmall)\n\n8.4 Switch AI per linking automatico\n- Collegamento tra componenti correlati\n- Generazione navigation tra stories\n- Suggerimenti per layout coerente\n\n*** MOTION & INTERACTION (10. Motion e Interaction Design) ***\n- Componenti con micro-interactions predefinite\n- Motion tokens estratti da Figma\n- Generazione di animazioni CSS/JS compatibili con framework scelto\n- Supporto per hover, click, focus e toggle states\n- Possibilità di generare animazioni avanzate usando:\n  - GSAP\n  - React Three Fiber\n  - Altri framework compatibili selezionati dall’AI in base alla necessità, senza esagerare\n- Switch dedicato per attivare/disattivare animazioni AI-generated\n- Nota: generazione animazioni tramite AI consuma crediti"
  ],
  section: "CORE FEATURES & LOGIC"
};
